#!/usr/bin/env sh

desktop_file() {
  find /usr/share/applications -name "*.desktop" 2>/dev/null \
  && find /usr/local/share/applications -name "*.desktop" 2>/dev/null \
  && find "$HOME/.local/share/applications" -name "*.desktop" 2>/dev/null \
  && find /var/lib/flatpak/exports/share/applications -name "*.desktop" 2>/dev/null \
  && find "$HOME/.local/share/flatpak/exports/share/applications" -name "*.desktop" 2>/dev/null
}

selected="$(desktop_file | sed 's/.desktop//g' | sort | fzf -e -i -m --reverse --delimiter / --with-nth -1)"
[ -z "$selected" ] && exit
cd || return
echo "$selected" | while read -r line ; do setsid xdg-open "$line".desktop ; done
